export type Product = {
  name: string;
  code: string;
  size: string;
  material: string;
  color: string;
  price: string;
  imagePath: string;
  description?: string;
  descriptionDe?: string;
};

export function getProductDescription(
  product: Pick<Product, "description" | "descriptionDe">,
  language: "en" | "de",
) {
  return language === "de" ? product.descriptionDe ?? product.description : product.description;
}

export const products: Product[] = [
  { name: "Diva", code: "BRM01", size: "Medium, L10 x H8", material: "Sabutan", color: "Black", price: "140€", imagePath: "/img/collection/BRM01.png", description: "a handcrafted woven bayong handbag with a bold black and white design, vibrant blue accents and elegant details.", descriptionDe: "Eine handgewebte Bayong-Handtasche mit einem ausdrucksstarken schwarz-weißen Design, leuchtend blauen Akzenten und eleganten Details." },
  { name: "Eleganz", code: "BRA01", size: "Small, L10 x H9", material: "Sabutan", color: "Stripe Black/White", price: "130€", imagePath: "/img/collection/BRA01.png", description: "Handcrafted Bayong bag featuring a stylish woven design with a chic fashion-inspired pattern and convenient top handle.", descriptionDe: "Eine handgefertigte Bayong-Tasche mit stilvollem Webdesign, schickem modischem Muster und praktischem Tragegriff." },
  { name: "Rosenliebe", code: "BRM02", size: "L5 x H4.5", material: "Sabutan", color: "Black", price: "130€", imagePath: "/img/collection/BRM02.png", description: "Handcrafted Bayong bag with striking black woven design, a beautiful pink rose motif, and an elegant red and gold chain handle.", descriptionDe: "Eine handgefertigte Bayong-Tasche mit auffälligem schwarzem Webdesign, einem wunderschönen rosa Rosenmotiv und einer eleganten rot-goldenen Kette." },
  { name: "Anmut", code: "BRK01", size: "H12 x 3", material: "Buntal Fiber", color: "Black", price: "140€", imagePath: "/img/collection/BRK01-A.png", description: "The artistic design featuring a woman and floral details gives the bag a romantic and timeless character.", descriptionDe: "Das künstlerische Design mit einer Frau und floralen Details verleiht der Tasche einen romantischen und zeitlosen Charakter." },
  { name: "Blütenlieb", code: "BRK01", size: "H12 x 3", material: "Buntal Fiber", color: "Off-white", price: "140€", imagePath: "/img/collection/BRK01-B.png", description: "handcrafted bayong bag with a charming floral design, woven details and elegant cream and black woven.", descriptionDe: "Eine handgefertigte Bayong-Tasche mit charmantem Blumendesign, Webdetails und eleganten cremefarbenen und schwarzen Elementen." },
  { name: "Blümenpoesie", code: "BRM03", size: "L14 x H10", material: "Sabutan", color: "Black", price: "140€", imagePath: "/img/collection/BRM03.png", description: "Handcrafted Bayong bag with a striking floral design, woven details, and elegant black handles.", descriptionDe: "Eine handgefertigte Bayong-Tasche mit auffälligem Blumendesign, Webdetails und eleganten schwarzen Griffen." },
  { name: "Nachtperle", code: "BRJ01", size: "L11 x H8", material: "Buntal Fiber", color: "Black with White", price: "140€", imagePath: "/img/collection/BRJ01.png", description: "Handcrafted Bayong bag with an elegant black and white woven pattern, a stylish gold tone clasp, and a graceful woman design.", descriptionDe: "Eine handgefertigte Bayong-Tasche mit elegantem schwarz-weißem Webmuster, stilvollem goldfarbenem Verschluss und anmutigem Frauendesign." },
  { name: "Künstblüte", code: "BRA02", size: "9x12", material: "Sabutan", color: "Pink", price: "140€", imagePath: "/img/collection/BRA02.png", description: "Handcrafted Bayong bag featuring a vibrant artistic design with a beautiful woman, floral details, and a natural wooden handle.", descriptionDe: "Eine handgefertigte Bayong-Tasche mit lebendigem künstlerischem Design, einer schönen Frau, floralen Details und einem natürlichen Holzgriff." },
  { name: "Blütenzauber", code: "BASB01", size: "9.5x14", material: "Sabutan", color: "Red with Dark Brown Handle", price: "130€", imagePath: "/img/collection/BASB01.png", description: "Handcrafted bayong bag with colorful floral design and elegant brown handle.", descriptionDe: "Eine handgefertigte Bayong-Tasche mit farbenfrohem Blumendesign und elegantem braunem Griff." },
  { name: "Nachtblüte", code: "BAS01", size: "8.5x10", material: "Sabutan", color: "Black with Blue", price: "120€", imagePath: "/img/collection/BAS01-A.png", description: "handcrafted Bayong bag with an elegant floral design, woven detailing and stylish black and blue finish.", descriptionDe: "Eine handgefertigte Bayong-Tasche mit elegantem Blumendesign, Webdetails und stilvollem schwarz-blauem Finish." },
  { name: "Sonnenblüte", code: "BAS01", size: "8.5x10", material: "Sabutan", color: "Black with Orange", price: "120€", imagePath: "/img/collection/BAS01-B.png", description: "Handcrafted Bayong bag featuring a striking orange floral design on a black woven base, with elegant handles and a gold-tone clasp.", descriptionDe: "Eine handgefertigte Bayong-Tasche mit auffälligem orangefarbenem Blumendesign auf schwarzem Webgrund, eleganten Griffen und goldfarbenem Verschluss." },
  { name: "Naturzauber", code: "BAP01", size: "10.5x12", material: "Pandan Leaves with Wood Handle", color: "Cream/Off-white Woven Accents", price: "120€", imagePath: "/img/collection/BAP01.png", description: "The woven texture and wooden handle create a timeless accessory that is perfect for everyday elegance or special occasions.", descriptionDe: "Die Webstruktur und der Holzgriff machen diese Tasche zu einem zeitlosen Accessoire für alltägliche Eleganz und besondere Anlässe." },
  { name: "Luna", code: "BAP02", size: "11x13.5", material: "Pandan Leaves", color: "Navy Blue", price: "120€", imagePath: "/img/collection/BAP02.png", description: "a handcrafted woven bayong featuring a colorful Filipina inspired design.", descriptionDe: "Eine handgewebte Bayong-Tasche mit farbenfrohem, von den Philippinen inspiriertem Design." },
  { name: "Blütenpracht", code: "BAP03", size: "15x10", material: "Pandan leaves with wood handle", color: "Pink", price: "120€", imagePath: "/img/collection/BAP03.png", description: "Handcrafted Bayong bag with a vibrant woven pattern, colorful floral design, and a natural wooden handle.", descriptionDe: "Eine handgefertigte Bayong-Tasche mit lebendigem Webmuster, farbenfrohem Blumendesign und natürlichem Holzgriff." },
  { name: "Bella", code: "BAPS04", size: "8.5x8.5", material: "Pandan Leaves", color: "Cream/Off-white Woven Accents", price: "120€", imagePath: "/img/collection/BAPS04.png", description: "A stylish handcrafted Bayong bag made from natural pandan leaves, featuring a striking woven design with colorful green, red, and yellow accents.", descriptionDe: "Eine stilvolle handgefertigte Bayong-Tasche aus natürlichen Pandanblättern mit einem auffälligen Webmuster und grünen, roten und gelben Akzenten." },
  { name: "Sonnenglück", code: "BAPHP01", size: "11x15", material: "Handwoven Pandan", color: "Cream/Off-white Woven Accents", price: "120€", imagePath: "/img/collection/BAPHP01.png", description: "Handcrafted Bayong bag with bright sunflower design, colorful plaid detail.", descriptionDe: "Eine handgefertigte Bayong-Tasche mit leuchtendem Sonnenblumendesign und farbenfrohem Karodetail." },
  { name: "Florentia", code: "BAPT01", size: "12x8", material: "Pandan Leaves", color: "Cream/Off-white Woven Accents", price: "120€", imagePath: "/img/collection/BAPT01.png", description: "Featuring an eye-catching arrangement of colorful flowers on a natural woven base.", descriptionDe: "Mit einer auffälligen Anordnung bunter Blumen auf einem natürlich gewebten Untergrund." },
  { name: "Zitronenzauber", code: "BZ001", size: "10x11", material: "Sabutan", color: "Cream/Off-white Woven Accents", price: "140€", imagePath: "/img/collection/BZ001.png", description: "Handcrafted bayong bag with a charming lemon and a floral design, woven texture and an elegant cream colored handle.", descriptionDe: "Eine handgefertigte Bayong-Tasche mit charmantem Zitronen- und Blumendesign, Webstruktur und elegantem cremefarbenem Griff." },
  { name: "Abendzauber", code: "BZ002", size: "9x14", material: "Buntal Fiber", color: "Dark Brown / Black Stripes", price: "140€", imagePath: "/img/collection/BZ002-A.png", description: "A sophisticated handcrafted Bayong bag featuring a rich dark brown woven pattern with elegant black detailing.", descriptionDe: "Eine elegante handgefertigte Bayong-Tasche mit einem tief dunkelbraunen Webmuster und stilvollen schwarzen Details." },
  { name: "Naturale", code: "BZ002", size: "9x14", material: "Sabutan", color: "Cream/Off-white Woven Accents", price: "140€", imagePath: "/img/collection/BZ002-B.png", description: "A sophisticated Bayong bag with beautifully woven natural finish and a warm wooden-style handle.", descriptionDe: "Eine elegante Bayong-Tasche mit einer schön gewebten natürlichen Oberfläche und einem warmen Holzgriff." },
  { name: "Amara", code: "FP001", size: "5.5x12", material: "Pandan", color: "Black/White Woven Accents", price: "110€", imagePath: "/img/collection/FP001.png", description: "Handcrafted Bayong bag with braided shoulder strap and an elegant brown-and-cream diamond pattern.", descriptionDe: "Eine handgefertigte Bayong-Tasche mit geflochtenem Schulterriemen und elegantem braun-cremefarbenem Rautenmuster." },
  { name: "Blütenkunst", code: "VB002", size: "9x16", material: "Pandan", color: "Brown woven accents", price: "120€", imagePath: "/img/collection/VB002.png", description: "Featuring a striking artistic design in vibrant blue and pink tones.", descriptionDe: "Mit einem auffälligen künstlerischen Design in leuchtenden Blau- und Rosatönen." },
  { name: "Handwoven clutch-A", code: "Handwoven-Clutch", size: "4x8", material: "Pandan", color: "Multicolor and off white woven accents", price: "35€", imagePath: "/img/collection/HandwovenClutch-A.png", description: "Handcrafted Bayong bag with colorful woven details and a chic off-white accent palette.", descriptionDe: "Eine handgefertigte Bayong-Tasche mit farbenfrohen Webdetails und einer stilvollen cremeweißen Farbpalette." },
  { name: "Handwoven clutch-B", code: "Handwoven-Clutch", size: "4x8", material: "Pandan", color: "Multicolor and off white woven accents", price: "35€", imagePath: "/img/collection/HandwovenClutch-B.png", description: "Handcrafted Bayong bag with colorful woven details and a chic off-white accent palette.", descriptionDe: "Eine handgefertigte Bayong-Tasche mit farbenfrohen Webdetails und einer stilvollen cremeweißen Farbpalette." },
  { name: "Flechstil", code: "Msb001", size: "9x8", material: "Pandan", color: "Black with White Woven Accents", price: "70€", imagePath: "/img/collection/Msb001-A.png", description: "The bag has a warm natural brown color, with a mix of dark chocolate brown, medium brown, tan, and light beige/cream woven together. The black trim adds contrast.", descriptionDe: "Die Tasche hat eine warme Naturbraunfarbe mit einer Mischung aus dunklem Schokoladenbraun, mittlerem Braun, Beige und hellem Beige beziehungsweise Creme, die miteinander verflochten sind. Der schwarze Rand setzt einen Kontrast." },
  { name: "Men's Sling Bag", code: "Msb001", size: "9x8", material: "Pandan", color: "Black with White Woven Accents", price: "70€", imagePath: "/img/collection/Msb001-B.png", description: "The distinctive brown and natural-toned woven pattern gives the bag a modern, masculine look.", descriptionDe: "Das auffällige Webmuster in Braun- und Naturtönen verleiht der Tasche einen modernen, maskulinen Look." },
  { name: "Luna blu", code: "BATS05", size: "8.5x10.5", material: "Sabutan", color: "Natural beige/tan woven body; Black flap and handle; Blue main design; Multicolor flower accent", price: "120€", imagePath: "/img/collection/BATS05.png", description: "featuring an elegant blue fashion-inspired design and a colorful handmade flower detail. A unique statement accessory that combines traditional Filipino craftsmanship with modern style.", descriptionDe: "Mit elegantem, von der Mode inspiriertem blauem Design und farbenfrohem handgefertigtem Blumendetail. Ein einzigartiges Accessoire, das traditionelle philippinische Handwerkskunst mit modernem Stil verbindet." },
];

export const productMaterials = Array.from(
  new Set(products.map((product) => product.material))
);

export const productColors = Array.from(
  new Set(products.map((product) => product.color))
);
